export const REQUEST_COLLECTIONS_PENDING = "REQUEST_COLLECTIONS_PENDING";
export const REQUEST_COLLECTIONS_SUCCESS = "REQUEST_COLLECTIONS_SUCCESS";
export const REQUEST_COLLECTIONS_FAILED = "REQUEST_COLLECTIONS_FAILED";
